title: Hello, world! I'm myoungiron
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "/myoungiron.github.io" # the subpath of your site, e.g. /blog
url: "http://www.myoungiron.com" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: myoungiron # add your name
author-img: myoungiron.jpg # add your photo
about-author: 繁华殆尽，静下心，编一行代码 # add description
twitter: # add your Twitter handle
facebook: # add your Facebook handle
github: myoungiron # add your Github handle
linkedin: # add your Linkedin handle
email: guo12210109@foxmail.com # add your Email address

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
