# Site settings
title: myoungiron
SEOTitle: myoungiron Blog
header-img: img/home-bg.jpg
email: guo12210109@foxmail.com
description: "java后台，热爱编程，热爱生活 | myoungiron | 这里是 @myoungiron 的个人博客，欢迎交流。"
keyword: " myoungiron, 博客, 个人网站, guozhaoyang,github pages "
url: "https://www.myoungiron.com"              # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'



# SNS settings
RSS: false
weibo_username:     myoungiron
zhihu_username:     myoungiron
github_username:    myoungiron
twitter_username:   myoungiron
#facebook_username:  huxpro
# linkedin_username:  firstname-lastname-idxxxx



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# Disqus settings
disqus_username: myoungiron

# Netease setttings




# Analytics settings
# Baidu Analytics 
# ba_track_id: [your track id]

# Google Analytics
#ga_track_id: 'UA-49627206-1'            # Format: UA-xxxxxx-xx
#ga_domain: huangxuan.me



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "繁华殆尽，静下心 <br> 写一行代码"
sidebar-avatar: /img/avatar-myoungiron.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    {
         title: "Werb",
         href: "https://github.com/Werb/"
     }
    ,{
        title: "Hux(theme author)",
        href: "http://http://huangxuan.me/"
    }
    
]
